# Generated by Django 5.0.4 on 2024-04-16 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomchat',
            name='chat_messages',
        ),
    ]
